from pydantic import BaseModel, Field


class ConversationMessage(BaseModel):
    role: str = Field(..., pattern="^(user|assistant)$")
    content: str


class QueryRequest(BaseModel):
    question: str = Field(..., min_length=1, max_length=2000)
    document_filter: list[str] | None = None
    top_k: int | None = None
    conversation_history: list[ConversationMessage] = Field(default_factory=list)
    debug: bool = False
    session_id: str | None = None


class SourceReference(BaseModel):
    document_name: str
    chunk_index: int
    text_excerpt: str
    similarity_score: float


class ConfidenceAssessment(BaseModel):
    score: float = Field(..., ge=0.0, le=1.0)
    level: str
    reasoning: str


class DebugChunk(BaseModel):
    document_name: str
    chunk_index: int
    text_excerpt: str
    similarity_score: float
    rerank_score: float | None = None


class DebugInfo(BaseModel):
    retrieved_chunks: list[DebugChunk]
    reranked_chunks: list[DebugChunk]
    similarity_scores: list[float]
    rerank_scores: list[dict]  # [{chunk_index, score}]
    final_selected_chunks: list[DebugChunk]


class EvaluationResult(BaseModel):
    grounded: bool
    hallucination: bool
    score: float = Field(..., ge=0.0, le=1.0)
    reasoning: str


class QueryResponse(BaseModel):
    answer: str
    sources: list[SourceReference]
    confidence: ConfidenceAssessment
    evaluation: EvaluationResult | None = None
    prompt_version: str | None = None
    evaluation_prompt_version: str | None = None
    disclaimer: str = (
        "This response is generated by an AI assistant and is based solely on the "
        "provided clinical documents. It is not a substitute for professional medical "
        "advice, diagnosis, or treatment. Always consult a qualified healthcare provider."
    )
    debug: DebugInfo | None = None
